# #docplaster
# #docregion
# #docregion no-rewriter
name: angular2_getting_started
description: QuickStart
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.15
  browser: ^0.10.0
# #enddocregion no-rewriter
  dart_to_js_script_rewriter: ^1.0.1
# #docregion no-rewriter
transformers:
- angular2:
    entry_points: web/main.dart
# #enddocregion no-rewriter
- dart_to_js_script_rewriter
