# #docregion , additions
name: angular2_tour_of_heroes
  # #enddocregion additions
description: Tour of Heroes
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
  # #docregion additions
dependencies:
  angular2: 2.0.0-beta.18
  # #enddocregion additions
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  # #docregion additions
  http: ^0.11.0
transformers:
- angular2:
    # #enddocregion additions
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    # #docregion additions
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
