dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
  matrix:
    - SCRIPT="lint"
    - SCRIPT="run-e2e-tests --fast"
before_install:
  - npm install -g gulp --no-optional
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install --no-optional
  - npm install --prefix public/docs/_examples
  - npm install --prefix public/docs/_examples/_protractor
  - npm run webdriver:update --prefix public/docs/_examples/_protractor
  - gulp add-example-boilerplate
script:
  - gulp $SCRIPT
