# #docregion
name: server_communication
description: Server Communication
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.18
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  http: ^0.11.3+3
  jsonpadding: ^0.1.0
  stream_transformers: ^0.3.0+3
  http_in_memory_web_api: ^0.0.1
# #docregion transformers
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
- dart_to_js_script_rewriter
