# #docregion
name: server_communication
description: Server Communication
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.6
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  http: ^0.11.3+3
  jsonpadding: ^0.1.0
  stream_transformers: ^0.3.0+3
  http_in_memory_web_api: ^0.0.1
transformers:
- angular2:
    platform_directives: 'package:angular2/common.dart#CORE_DIRECTIVES'
    platform_pipes: 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: 'web/main.dart'
- dart_to_js_script_rewriter
