name: dependency_injection
description: Dependency injection sample
version: 0.0.1
description: Dependency injection sample
dependencies:
  angular2: ^2.0.0-beta.6
  browser: ^0.10.0
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
dev_dependencies:
  test: any
