# #docplaster special plaster
# #docregion foo, bar
name: angular-getting-started
# #enddocregion foo
version: 0.0.1
dependencies:
# #docregion foo
  angular2:  ^2.2.0
  browser: ^0.10.0
# #enddocregion foo  
transformers:
- angular2:
    entry_points: web/main.dart
