name: attribute_directives
description: Attribute Directives
version: 0.0.1
dependencies:
  angular2: 2.0.0-beta.1
  browser: ^0.10.0
transformers:
- angular2:
    platform_directives: 'package:angular2/src/common/directives.dart#CORE_DIRECTIVES'
    entry_points: web/main.dart
